[package]
name = "reflection"
version = "0.1.0"
authors = ["lagobas <maxim.kolesnik90@gmail.com>"]
edition = "2018"

[dependencies]
simple-error = "0.1.9"
lazy_static = "1.4.0"
containers = { path = "../containers" }

[lib]
crate-type = ["dylib"]
proc-macro = true
