[package]
name = "plg_test"
version = "0.1.0"
authors = ["lagobas <maxim.kolesnik90@gmail.com>"]

[dependencies]
reflection = { path = "../reflection" }
reflection_proc = { path = "../reflection_proc" }
plugin_loader = { path = "../plugin_loader" }

[lib]
crate-type = ["dylib"]
