[package]
name = "containers"
version = "0.1.0"
authors = ["lagobas <maxim.kolesnik90@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1.0"
fnv = "1.0.*"
